## 📺 Video Reference
[Introduction to NumPy (YouTube)](https://youtu.be/VXU4LSAQDSc?si=-sqfsGVno7DLhJYT)

| Timestamp | Topic |
|-----------|-------|
| 0:00 – 1:31 | What NumPy is and why it's faster |
| 1:31 – 3:04 | Installing & importing NumPy |
| 3:04 – 5:58 | NumPy arrays vs Python lists |
| 5:58 – 9:44 | Array dimensions (0D, 1D, 2D, 3D) |
| 9:44 – 24:00 | Indexing & slicing |
| 24:09 – 30:50 | Arithmetic & vectorization |
| 30:50 – 39:47 | Comparisons & broadcasting |
| 39:47 – 43:43 | Aggregate functions |
| 43:52 – 51:43 | Boolean filtering |
| 52:07 – 60:00 | Random numbers & sampling |

Intro to DS (Course: SHALA 2020): https://www.youtube.com/live/zKSczEN4lks?si=8tCV7cRit5XATZQv

# Introduction to NumPy

**NumPy** (short for *Numerical Python*) is a library that makes working with numbers in Python much easier and faster.

### Why use NumPy instead of plain Python lists?
- **Speed** — NumPy's core is written in C, so it runs much faster than a regular Python loop.
- **Less code** — Instead of writing a `for` loop to do maths on every item, NumPy lets you do it in one line.
- **More features** — Built-in functions for statistics, linear algebra, random numbers, and more.

### Installation
If you're running this notebook in Google Colab, run the cell below. (NumPy is already installed in most environments.)

In [3]:
!pip install numpy

### Importing NumPy
By convention, NumPy is always imported with the alias `np`.  
Every NumPy function will then be called as `np.something()`.

In [4]:
# Import NumPy and give it the short alias 'np'
import numpy as np

# Check which version you have installed
print("NumPy version:", np.__version__)

NumPy version: 2.4.4


---
## 1. NumPy Arrays vs Python Lists

The most important thing to understand first: a NumPy **array** looks like a Python list, but it behaves very differently when you do maths on it.

| Python list | NumPy array |
|-------------|-------------|
| `* 2` duplicates the list | `* 2` multiplies every element by 2 |
| Slower for numbers | Much faster |
| No built-in maths functions | Hundreds of built-in maths functions |

In [5]:
# ── Python list behaviour ──────────────────────────────────────────
my_list = [1, 2, 3, 4]
print("Original list:", my_list)

# Multiplying a list by 2 REPEATS it — not what we usually want for maths
my_list_times_2 = my_list * 2
print("List × 2:", my_list_times_2)   # [1, 2, 3, 4, 1, 2, 3, 4]

# ── NumPy array behaviour ───────────────────────────────────────────
my_array = np.array([1, 2, 3, 4])
print("\nOriginal array:", my_array)
print("Type:", type(my_array))         # <class 'numpy.ndarray'>

# Multiplying an array by 2 multiplies EVERY ELEMENT — exactly what we want
my_array_times_2 = my_array * 2
print("Array × 2:", my_array_times_2)  # [2, 4, 6, 8]

Original list: [1, 2, 3, 4]
List × 2: [1, 2, 3, 4, 1, 2, 3, 4]

Original array: [1 2 3 4]
Type: <class 'numpy.ndarray'>
Array × 2: [2 4 6 8]


---
## 2. Multidimensional Arrays

NumPy arrays can have multiple *dimensions*. You can think of:
- **0D** → a single value (a point)
- **1D** → a row of values (a list)
- **2D** → rows *and* columns (a table / spreadsheet)
- **3D** → a stack of tables (like a cube)

The number of dimensions is stored in `.ndim`, and the size of each dimension is stored in `.shape`.

In [6]:
# 0-Dimensional array — just a single value
zero_d = np.array(42)
print("0D array:", zero_d)
print("Number of dimensions:", zero_d.ndim)   # 0
print("Shape:", zero_d.shape)                  # ()

0D array: 42
Number of dimensions: 0
Shape: ()


In [7]:
# 1-Dimensional array — like a normal list
one_d = np.array([10, 20, 30, 40])
print("1D array:", one_d)
print("Number of dimensions:", one_d.ndim)    # 1
print("Shape:", one_d.shape)                   # (4,)  ← 4 elements

1D array: [10 20 30 40]
Number of dimensions: 1
Shape: (4,)


In [8]:
# 2-Dimensional array — rows and columns (a matrix)
# Think of it as a table with 3 rows and 3 columns.
two_d = np.array([
    ['A', 'B', 'C'],   # row 0
    ['D', 'E', 'F'],   # row 1
    ['G', 'H', 'I'],   # row 2
])
print("2D array (matrix):\n", two_d)
print("Dimensions:", two_d.ndim)   # 2
print("Shape:", two_d.shape)       # (3, 3) ← 3 rows, 3 columns

2D array (matrix):
 [['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]
Dimensions: 2
Shape: (3, 3)


In [9]:
# 3-Dimensional array — a stack of matrices
# Think of it as 2 layers, each layer has 3 rows and 3 columns.
three_d = np.array([
    [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],   # layer 0
    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],   # layer 1
])
print("3D array:\n", three_d)
print("Dimensions:", three_d.ndim)   # 3
print("Shape:", three_d.shape)       # (2, 3, 3) ← 2 layers, 3 rows, 3 columns

3D array:
 [[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]]
Dimensions: 3
Shape: (2, 3, 3)


> **⚠️ Important:** Every row in a NumPy array must have the same number of elements.  
> If your rows have different lengths, NumPy will raise an error.

In [10]:
# ── Fun example: 2D array of emojis ──────────────────────────────────
# NumPy can store any data type, even strings (or emoji strings)
emoji = np.array([
    ['🌕', '🌖', '🌗', '🌘'],
    ['🌑', '🌒', '🌓', '🌔'],
])
print("Emoji array:\n", emoji)
print("Shape:", emoji.shape)   # (2, 4)

Emoji array:
 [['🌕' '🌖' '🌗' '🌘']
 ['🌑' '🌒' '🌓' '🌔']]
Shape: (2, 4)


---
## 3. Indexing & Slicing

Indexing means **picking specific elements** from an array.  
Slicing means **picking a range** of elements.

### How indexing works
- Like Python lists, NumPy uses **0-based indexing** (first element is index `0`)
- For multi-dimensional arrays, use `array[row, column]` — this is faster than `array[row][column]`

In [11]:
# Set up a 4×4 grid of numbers to practise with
number_array = np.array([
    [ 1,  2,  3,  4],   # row 0
    [ 5,  6,  7,  8],   # row 1
    [ 9, 10, 11, 12],   # row 2
    [13, 14, 15, 16],   # row 3
])
print(number_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [12]:
# ── Selecting whole rows ─────────────────────────────────────────────
print("Row 0 (first row):", number_array[0])    # [ 1  2  3  4]
print("Row 1:", number_array[1])                 # [ 5  6  7  8]
print("Row 3 (last row):", number_array[3])      # [13 14 15 16]

# Negative indexing: -1 means "last", -2 means "second to last"
print("\nLast row (index -1):", number_array[-1])
print("Second-to-last row (index -2):", number_array[-2])

Row 0 (first row): [1 2 3 4]
Row 1: [5 6 7 8]
Row 3 (last row): [13 14 15 16]

Last row (index -1): [13 14 15 16]
Second-to-last row (index -2): [ 9 10 11 12]


In [13]:
# ── Selecting a single element ──────────────────────────────────────
# Syntax: array[row, column]
print("Element at row 0, col 0:", number_array[0, 0])   # 1
print("Element at row 1, col 2:", number_array[1, 2])   # 7
print("Element at row 3, col 3:", number_array[3, 3])   # 16

Element at row 0, col 0: 1
Element at row 1, col 2: 7
Element at row 3, col 3: 16


In [14]:
# ── Row slicing: array[start:end:step] ───────────────────────────────
# The 'end' index is EXCLUSIVE (not included in the result).

print("Rows 0 to 2 (not including 3):")
print(number_array[0:3])       # rows 0, 1, 2

print("\nRows 1 to end:")
print(number_array[1:])        # rows 1, 2, 3

print("\nEvery other row (step=2):")
print(number_array[::2])       # rows 0, 2

print("\nReversed (step=-1):")
print(number_array[::-1])      # rows 3, 2, 1, 0

Rows 0 to 2 (not including 3):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Rows 1 to end:
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Every other row (step=2):
[[ 1  2  3  4]
 [ 9 10 11 12]]

Reversed (step=-1):
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [15]:
# ── Column slicing: array[:, column] ─────────────────────────────────
# The colon ':' before the comma means "all rows"

print("All values in column 0:", number_array[:, 0])    # [ 1  5  9 13]
print("All values in column 3:", number_array[:, 3])    # [ 4  8 12 16]
print("Last column:", number_array[:, -1])              # same as column 3

print("\nFirst 3 columns:")
print(number_array[:, 0:3])

print("\nEvery other column:")
print(number_array[:, ::2])

All values in column 0: [ 1  5  9 13]
All values in column 3: [ 4  8 12 16]
Last column: [ 4  8 12 16]

First 3 columns:
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]

Every other column:
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [16]:
# ── Selecting a rectangular region (rows AND columns) ────────────────
# Syntax: array[row_start:row_end, col_start:col_end]

print("Top-left 2×2 block:")
print(number_array[0:2, 0:2])   # [[ 1  2], [ 5  6]]

print("\nBottom-right 2×2 block:")
print(number_array[2:, 2:])     # [[11 12], [15 16]]

print("\nTop-right 2×2 block:")
print(number_array[0:2, 2:])    # [[ 3  4], [ 7  8]]

Top-left 2×2 block:
[[1 2]
 [5 6]]

Bottom-right 2×2 block:
[[11 12]
 [15 16]]

Top-right 2×2 block:
[[3 4]
 [7 8]]


---
## 4. Indexing Challenge 🧩

Can you find the hidden word in this 3D array?  
*Hint: use `array[layer, row, column]`*

In [17]:
letters = np.array([
    [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '_']],
])

# Each index is [layer, row, column]
# Chain indexing:          letters[0][0][0]   works, but is slower
# Multidimensional indexing: letters[0, 0, 0]  is preferred

print("letters[0, 0, 0] =", letters[0, 0, 0])   # A
print("letters[2, 2, 2] =", letters[2, 2, 2])   # _

# Combine letters to spell 'CODE'
word = letters[0, 0, 2] + letters[1, 1, 2] + letters[0, 1, 0] + letters[0, 1, 1]
print("Hidden word:", word)   # CODE

letters[0, 0, 0] = A
letters[2, 2, 2] = _
Hidden word: CODE


---
## 5. Arithmetic & Vectorization

**Vectorization** means applying an operation to every element of an array *at once*, without writing a loop.

### Scalar arithmetic
A *scalar* is just a single number. When you do `array + scalar`, NumPy adds that number to every element.

In [18]:
arr = np.array([1, 2, 3, 4, 5])

print("Original:", arr)
print("arr + 10:", arr + 10)    # add 10 to every element
print("arr - 3:", arr - 3)      # subtract 3 from every element
print("arr * 2:", arr * 2)      # double every element
print("arr / 4:", arr / 4)      # divide every element by 4
print("arr ** 2:", arr ** 2)    # square every element

Original: [1 2 3 4 5]
arr + 10: [11 12 13 14 15]
arr - 3: [-2 -1  0  1  2]
arr * 2: [ 2  4  6  8 10]
arr / 4: [0.25 0.5  0.75 1.   1.25]
arr ** 2: [ 1  4  9 16 25]


### Built-in math functions
NumPy includes many common maths functions — all of them work element-wise on arrays.

In [19]:
nums = np.array([1.0, 4.0, 9.0, 16.0])

print("Square root:", np.sqrt(nums))     # [1, 2, 3, 4]
print("Pi constant:", np.pi)             # 3.14159...

decimals = np.array([1.2, 2.5, 3.8])
print("\nOriginal:", decimals)
print("Rounded:", np.round(decimals))    # [1, 2, 4] — rounds to nearest integer
print("Floor (round down):", np.floor(decimals))   # [1, 2, 3]
print("Ceil (round up):", np.ceil(decimals))       # [2, 3, 4]

Square root: [1. 2. 3. 4.]
Pi constant: 3.141592653589793

Original: [1.2 2.5 3.8]
Rounded: [1. 2. 4.]
Floor (round down): [1. 2. 3.]
Ceil (round up): [2. 3. 4.]


In [20]:
# ── Exercise: Area of circles ────────────────────────────────────────
# Formula: area = π × r²
# With NumPy we can calculate the area for ALL radii in one line!

radii = np.array([1, 2, 3, 5, 10])
areas = np.pi * radii ** 2    # ** is evaluated before *, just like in normal maths

print("Radii:", radii)
print("Areas:", np.round(areas, 2))   # rounded to 2 decimal places

Radii: [ 1  2  3  5 10]
Areas: [  3.14  12.57  28.27  78.54 314.16]


### Element-wise operations on two arrays
When you add/subtract/multiply two arrays of the **same shape**, NumPy combines the elements at each matching position.

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a:", a)
print("b:", b)
print("a + b:", a + b)     # [5, 7, 9]   — adds matching positions
print("a - b:", a - b)     # [-3, -3, -3]
print("a * b:", a * b)     # [4, 10, 18]  — NOT matrix multiplication
print("a / b:", a / b)     # [0.25, 0.4, 0.5]
print("a ** b:", a ** b)   # [1, 32, 729]  — 1^4, 2^5, 3^6

a: [1 2 3]
b: [4 5 6]
a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]
a ** b: [  1  32 729]


---
## 6. Comparison Operators

You can compare every element of an array to a value in one go.  
The result is a **boolean array** — an array of `True` / `False` values.

In [22]:
scores = np.array([91, 55, 100, 73, 82, 64])
print("Scores:", scores)

print("\nscores == 100 (which scored perfectly?):", scores == 100)
print("scores >= 60 (passing grades?):", scores >= 60)
print("scores < 60 (failing grades?):", scores < 60)

Scores: [ 91  55 100  73  82  64]

scores == 100 (which scored perfectly?): [False False  True False False False]
scores >= 60 (passing grades?): [ True False  True  True  True  True]
scores < 60 (failing grades?): [False  True False False False False]


In [23]:
# You can use boolean arrays to UPDATE elements in-place.
# Example: any score below 60 gets set to 0 (failed).

scores = np.array([91, 55, 100, 73, 82, 64])
print("Before:", scores)

scores[scores < 60] = 0   # only the element 55 meets this condition
print("After (scores < 60 → 0):", scores)

Before: [ 91  55 100  73  82  64]
After (scores < 60 → 0): [ 91   0 100  73  82  64]


---
## 7. Broadcasting

**Broadcasting** is how NumPy handles arithmetic between arrays of *different shapes*.  
Instead of raising an error, NumPy "stretches" the smaller array to match the bigger one.

### The rules (read dimensions right to left):
1. Two dimensions are **compatible** if they are equal, OR one of them is `1`.
2. A missing dimension is treated as size `1`.

Let's see this visually:

In [24]:
# ── Compatible shapes: (1,4) and (4,1) ──────────────────────────────
# row_array is 1 row × 4 columns
row_array = np.array([[1, 2, 3, 4]])       # shape (1, 4)
# col_array is 4 rows × 1 column
col_array = np.array([[1], [2], [3], [4]]) # shape (4, 1)

print("row_array shape:", row_array.shape)
print("col_array shape:", col_array.shape)
print("\nrow × col (broadcasting creates a 4×4 grid):")
print(row_array * col_array)
# NumPy stretches row_array down 4 rows and col_array across 4 columns

row_array shape: (1, 4)
col_array shape: (4, 1)

row × col (broadcasting creates a 4×4 grid):
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [25]:
# ── Incompatible shapes — will raise an error ────────────────────────
array_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  # shape (2, 4)
array_2 = np.array([[1], [2], [3], [4]])            # shape (4, 1)

print("array_1 shape:", array_1.shape)   # (2, 4)
print("array_2 shape:", array_2.shape)   # (4, 1)

# Reading right-to-left:
# Position 1 (rightmost): 4 vs 1 → compatible (1 stretches to 4)
# Position 2: 2 vs 4 → NOT compatible (neither is 1)
# → Error!

# Uncomment the line below to see the error:
# print(array_1 * array_2)
print("These shapes are NOT compatible — would raise ValueError.")

array_1 shape: (2, 4)
array_2 shape: (4, 1)
These shapes are NOT compatible — would raise ValueError.


In [26]:
# ── Compatible again: (4,4) and (4,1) ───────────────────────────────
array_1 = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]])  # shape (4, 4)
array_2 = np.array([[1], [2], [3], [4]])  # shape (4, 1)

print("array_1 shape:", array_1.shape)   # (4, 4)
print("array_2 shape:", array_2.shape)   # (4, 1)

# Position 1: 4 vs 1 → 1 stretches to 4 ✔
# Position 2: 4 vs 4 → equal ✔
print("\nResult:")
print(array_1 * array_2)
# Each row of array_1 is multiplied by the matching row multiplier

array_1 shape: (4, 4)
array_2 shape: (4, 1)

Result:
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [27]:
# ── Broadcasting exercise: build a multiplication table ─────────────
rows = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])   # shape (1, 10)
cols = np.array([[1], [2], [3], [4], [5],
                 [6], [7], [8], [9], [10]])            # shape (10, 1)

table = rows * cols   # broadcasting creates a (10, 10) result
print("Multiplication table (1–10):")
print(table)

Multiplication table (1–10):
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


---
## 8. Aggregate Functions

Aggregate functions **summarise** your data — they take an array and return a single number (or one number per row/column).

| Function | What it does |
|----------|-------------|
| `np.sum()` | Total of all values |
| `np.mean()` | Average value |
| `np.std()` | Standard deviation (how spread out the values are) |
| `np.var()` | Variance (std²) |
| `np.min()` | Smallest value |
| `np.max()` | Largest value |
| `np.argmin()` | Index of the smallest value |
| `np.argmax()` | Index of the largest value |

In [28]:
data = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10]
])
print("Data:\n", data)
print("\nSum of ALL values:", np.sum(data))      # 55
print("Mean (average):", np.mean(data))           # 5.5
print("Std deviation:", np.std(data))             # ~3.02
print("Variance:", np.var(data))                  # ~9.17
print("Minimum:", np.min(data))                   # 1
print("Maximum:", np.max(data))                   # 10
print("Index of minimum:", np.argmin(data))       # 0  (flattened index)
print("Index of maximum:", np.argmax(data))       # 9  (flattened index)

Data:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Sum of ALL values: 55
Mean (average): 5.5
Std deviation: 2.8722813232690143
Variance: 8.25
Minimum: 1
Maximum: 10
Index of minimum: 0
Index of maximum: 9


In [29]:
# ── Aggregate along an axis ──────────────────────────────────────────
# axis=0 → apply the function DOWN each column (combine rows)
# axis=1 → apply the function ACROSS each row (combine columns)

data = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10]
])

print("Sum of each COLUMN (axis=0):", np.sum(data, axis=0))
# → [7, 9, 11, 13, 15]  (1+6, 2+7, 3+8, ...)

print("Sum of each ROW    (axis=1):", np.sum(data, axis=1))
# → [15, 40]  (1+2+3+4+5, 6+7+8+9+10)

Sum of each COLUMN (axis=0): [ 7  9 11 13 15]
Sum of each ROW    (axis=1): [15 40]


---
## 9. Boolean Filtering

Boolean filtering (also called *boolean indexing*) lets you **select only the elements that match a condition** — like a database `WHERE` clause.

In [30]:
temperatures = np.array([22, 35, 18, 40, 28, 15, 31])
print("All temperatures:", temperatures)

# Step 1: Create a boolean mask — True where the condition is met
hot = temperatures > 30
print("Temperatures > 30:", hot)   # [F F F T F F T]

# Step 2: Use the mask to filter the array
print("Hot days only:", temperatures[hot])   # [35 40 31]

# You can do this in one line too:
print("Cold days only:", temperatures[temperatures < 20])   # [18 15]

All temperatures: [22 35 18 40 28 15 31]
Temperatures > 30: [False  True False  True False False  True]
Hot days only: [35 40 31]
Cold days only: [18 15]


In [31]:
# ── Multiple conditions ──────────────────────────────────────────────
# Use & for AND,  | for OR,  ~ for NOT
# IMPORTANT: wrap each condition in parentheses!

temperatures = np.array([22, 35, 18, 40, 28, 15, 31])

mild = (temperatures >= 20) & (temperatures <= 30)
print("Mild days (20–30°C):", temperatures[mild])   # [22 28]

extreme = (temperatures < 18) | (temperatures > 38)
print("Extreme days (<18 or >38°C):", temperatures[extreme])   # [40 15]

Mild days (20–30°C): [22 28]
Extreme days (<18 or >38°C): [40 15]


In [32]:
# ── np.where() — keep the shape, replace values ──────────────────────
# np.where(condition, value_if_true, value_if_false)
# Unlike boolean indexing, this keeps the array the same size.

scores = np.array([88, 45, 72, 33, 95, 60])
print("Scores:", scores)

# Replace failing scores (<60) with 'FAIL' label... using numbers:
result = np.where(scores >= 60, scores, 0)   # keep score if passing, else 0
print("After np.where:", result)   # [88  0 72  0 95 60]

# You can also substitute strings:
labels = np.where(scores >= 60, "pass", "fail")
print("Labels:", labels)   # ['pass' 'fail' 'pass' 'fail' 'pass' 'pass']

Scores: [88 45 72 33 95 60]
After np.where: [88  0 72  0 95 60]
Labels: ['pass' 'fail' 'pass' 'fail' 'pass' 'pass']


---
## 10. Random Numbers & Sampling

NumPy can generate random numbers — useful for simulations, shuffling data, and setting up test data.

The modern way to generate random numbers in NumPy is with `np.random.default_rng()`, which creates a **random number generator (RNG)** object.

> **Tip:** Pass a *seed* to `default_rng(seed)` to get the same random numbers every time — great for reproducible results.

In [33]:
# Create a random number generator
# Setting a seed means the output is the same every time you run this
rng = np.random.default_rng(seed=42)

# Random integers between low (inclusive) and high (exclusive)
dice_rolls = rng.integers(low=1, high=7, size=10)
print("10 dice rolls (1–6):", dice_rolls)

10 dice rolls (1–6): [1 5 4 3 3 6 1 5 2 1]


In [34]:
rng = np.random.default_rng(seed=42)

# Random floats between 0.0 and 1.0
random_floats = rng.random(size=5)
print("5 random floats [0, 1):", np.round(random_floats, 3))

# Random floats in a custom range [low, high)
temperatures = rng.uniform(low=20.0, high=40.0, size=5)
print("5 random temperatures [20, 40):", np.round(temperatures, 1))

5 random floats [0, 1): [0.774 0.439 0.859 0.697 0.094]
5 random temperatures [20, 40): [39.5 35.2 35.7 22.6 29. ]


In [35]:
rng = np.random.default_rng(seed=7)

# Shuffle an array (modifies it in-place)
cards = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Before shuffle:", cards)
rng.shuffle(cards)
print("After shuffle:", cards)

Before shuffle: [ 1  2  3  4  5  6  7  8  9 10]
After shuffle: [ 9  1  8  2  4  7  3  5  6 10]


In [36]:
rng = np.random.default_rng(seed=99)

# Choose random items from an array
fruits = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])

# Pick 3 items without replacement (no duplicates)
sample = rng.choice(fruits, size=3, replace=False)
print("Random sample of 3 fruits:", sample)

# Pick 5 items WITH replacement (duplicates allowed)
sample_wr = rng.choice(fruits, size=5, replace=True)
print("Random sample with replacement:", sample_wr)

Random sample of 3 fruits: ['elderberry' 'cherry' 'date']
Random sample with replacement: ['cherry' 'elderberry' 'elderberry' 'elderberry' 'date']


---
## 📝 Summary

| Concept | Key idea | Example |
|---------|----------|---------|
| **Array creation** | `np.array([...])` | `np.array([1, 2, 3])` |
| **Dimensions** | `.ndim` & `.shape` | `arr.shape → (3, 4)` |
| **Indexing** | `arr[row, col]` | `arr[0, 1]` |
| **Slicing** | `arr[start:end:step]` | `arr[::-1]` (reverse) |
| **Scalar ops** | Applied to every element | `arr * 2` |
| **Element-wise ops** | Between two same-shape arrays | `a + b` |
| **Comparisons** | Returns boolean array | `arr > 5` |
| **Broadcasting** | Stretch smaller array to match larger | `(1,4) × (4,1) → (4,4)` |
| **Aggregates** | Summarise to one value | `np.sum(arr, axis=0)` |
| **Boolean filtering** | Select by condition | `arr[arr > 3]` |
| **np.where** | Conditional replace | `np.where(cond, a, b)` |
| **Random** | Generate random data | `rng.integers(1, 7, 10)` |