Video reference: https://youtu.be/VXU4LSAQDSc?si=-sqfsGVno7DLhJYT
1. Introduction & Setup
- 0:00:00 – 0:01:31 — What NumPy Is, Why It Exists, Performance Motivation
- 0:01:31 – 0:02:38 — Installing NumPy & Importing
- 0:02:38 – 0:03:04 — Checking NumPy Version

2. NumPy Arrays vs Python Lists
- 0:03:04 – 0:05:11 — Lists vs Arrays: Vectorization, Speed, Memory
- 0:05:11 – 0:05:58 — Creating Arrays & Scalar Operations

3. Array Dimensions & Structure
- 0:05:58 – 0:08:48 — 0D, 1D, 2D, 3D Arrays Explained
- 0:08:48 – 0:09:44 — Shape, ndim, Structural Constraints

4. Indexing & Slicing
- 0:09:44 – 0:11:22 — Indexing: Chain vs Multidimensional
- 0:11:22 – 0:12:58 — Multidimensional Indexing Exercise
- 0:12:58 – 0:15:10 — Row Slicing Basics
- 0:15:10 – 0:17:03 — Advanced Row Slicing (Steps, Reverse)
- 0:17:03 – 0:19:29 — Column Selection & Slicing
- 0:19:29 – 0:21:37 — Advanced Column Slicing
- 0:21:37 – 0:24:00 — Combined Row & Column Slicing (Matrix Regions)

5. Arithmetic & Vectorization
- 0:24:09 – 0:26:10 — Scalar Arithmetic with Arrays
- 0:26:10 – 0:27:56 — Vectorized Math Functions & Constants
- 0:27:56 – 0:29:12 — Vectorization Exercise (Circle Area)
- 0:29:12 – 0:30:50 — Elementwise Array Operations

6. Comparisons & Broadcasting
- 0:30:50 – 0:33:25 — Comparison Operators & Boolean Arrays
- 0:33:25 – 0:39:39 — Broadcasting Rules & Shape Compatibility
- 0:39:39 – 0:39:47 — Broadcasting Exercise (Multiplication Table)

7. Aggregations & Reduction
- 0:39:47 – 0:43:43 — Aggregation Functions: sum, mean, std, min/max, argmin/argmax

8. Boolean Filtering
- 0:43:52 – 0:46:22 — Boolean Indexing
- 0:46:22 – 0:48:22 — Multiple Conditions & Logical Operators
- 0:48:22 – 0:51:43 — Preserving Shape with np.where()

9. Random Numbers & Sampling
- 0:52:07 – 0:54:25 — Random Integers & default_rng
- 0:54:25 – 0:56:32 — Random Floats, Uniform Distribution, Seeds
- 0:56:32 – 0:57:30 — Shuffling Arrays
- 0:57:30 – 1:00:00 — Random Choice (1D & 2D Examples)

# Introduction to NumPY

**Installing NumPY in Collab**

In [2]:
!pip3 install NumPY

In [3]:
# NumPY is short for Numerical Python. It is a Python Library used for numerical computing and data processing in Python.
# Importing NumPY Library, NumpY is faster than Native Python as it's core is written in C.
import numpy as np

In [4]:
# Identifying the current version of NumPY
print(np.__version__)

2.0.2


In [5]:
# Creating a sequence of numbers using array function and then multply each element by two in the array.
# An array is like an list, or like a sequence of numbers which is more powerful than say an list

# For Example, operation with lists:
my_list = [1, 2, 3, 4]
print(f"My List: {my_list}")
# Multiply the list elements with 2:
my_list = my_list * 2
print(f"\nNew List is: {my_list}")
print("\nNote that this dosn't give us the desired output.")

# Now let's try the same thing with Arrays in the NumPY Library
my_array = np.array([1, 2, 3, 4])
print("\nOriginal Array: ", my_array)
print("\nData Type is: ", type(my_array))
my_array = my_array * 2
print("\nModified Array is: ", my_array)

My List: [1, 2, 3, 4]

New List is: [1, 2, 3, 4, 1, 2, 3, 4]

Note that this dosn't give us the desired output.

Original Array:  [1 2 3 4]

Data Type is:  <class 'numpy.ndarray'>

Modified Array is:  [2 4 6 8]


# Multidimensional Arrays

In [6]:
# Zero Dimensional Array
zero = np.array('A')
print(f"Zero-Dimensional Array: \n{zero}")
print(zero.ndim) # ndim stands for Number of Dimensions

Zero-Dimensional Array: 
A
0


In [7]:
# One Dimensional Array
one = np.array(['A', 'B', 'C'])
print(f"One-Dimensional Array: \n{one}")
print(type(one)) #nd stands for N - Dimensions
print(one.ndim)

One-Dimensional Array: 
['A' 'B' 'C']
<class 'numpy.ndarray'>
1


In [8]:
# Two Dimensional Array, also reffered to as matrices
two = np.array([['A', 'B', 'C'],
                ['D', 'E', 'F'],
                ['G', 'H', 'I']])
print("This is a two-dimensional array, also called a matrix.")
print(f"Two-Dimensional Array: \n{two}")
print(two.ndim)

This is a two-dimensional array, also called a matrix.
Two-Dimensional Array: 
[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]
2


In [9]:
# Lol, creating an array of emoji's:
emoji = np.array([['🌖' '🌕' '🌖' '🌖'], ['🌕' '🌘' '🌘' '🌔']])
print(emoji)

[['🌖🌕🌖🌖']
 ['🌕🌘🌘🌔']]


In [10]:
# Three Dimensional Array - Incorrect
'''
three = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z']]]) #Returns Error
print(three.ndim)
'''

"\nthree = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],\n                [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],\n                [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z']]]) #Returns Error\nprint(three.ndim)\n"

In [11]:
# Three Dimensional Array
three = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '_']]])
print(three.shape)
print(three.ndim)

(3, 3, 3)
3


In [12]:
# Three Dimensional Array - Understanding the Shape Function
three = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']]])
print(three.shape)
print(three.ndim)

(2, 3, 3)
3


# Basic Operations on Arrays

In [13]:
# Three Dimensional Array - Accessing an Element
three = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])
print(three[0][0][0]) #Accessing an element in python using chain indexing
print(three[0, 0, 0])# Multidimensional Indexing, faster than chain indexing
word = three[0, 0, 2] + three[1, 1, 2] + three[0, 1, 0] + three[0, 1, 1] # Getting the word 'CODE' from the tensor.
print("The word is:", word)

A
A
The word is: CODE


In [14]:
# Initialize Number Array
number_array = np.array([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12],
                         [13, 14, 15, 16]])

In [15]:
print(f"Row 1(Index 0): {number_array[0]}")
print(f"Row 2(Index 1): {number_array[1]}")
print(f"Row 3(Index 2): {number_array[2]}")
print(f"Row 4(Index 3): {number_array[3]}")
# Note Index 4 will be out of bounds in this case and will return an error.
# Negative Indexing
print(f"\nLast Row: {number_array[-1]}")
print(f"Second Last Row: {number_array[-2]}")
print(f"Second Row: {number_array[-3]}")
print(f"First Row: {number_array[-4]}\n")

Row 1(Index 0): [1 2 3 4]
Row 2(Index 1): [5 6 7 8]
Row 3(Index 2): [ 9 10 11 12]
Row 4(Index 3): [13 14 15 16]

Last Row: [13 14 15 16]
Second Last Row: [ 9 10 11 12]
Second Row: [5 6 7 8]
First Row: [1 2 3 4]



In [16]:
# Slicing with number_array: number_array[Start:End:Step]
print(number_array[0: 3]) # First 3 rows, the ending index is exclusive, i.e., rows 0, 1 and 2.
print(number_array[1: 4])
print(number_array[0:])
print(number_array[0: 4: 2])
print(number_array[::2])
print(number_array[::-1]) # Reversing
print(number_array[::-2]) # Reverse and select every 2nd row

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[13 14 15 16]
 [ 5  6  7  8]]


In [17]:
# Column Selection
print(number_array[0, 0]) #number_array[row, column]
print(number_array[:, 0]) #Select all rows and access column 0
print(number_array[:, 1]) #Select all rows and access column 1
print(number_array[:, 2]) #Select all rows and acess column 2
print(number_array[:, 3]) #Select all rows and acess column 3
print(number_array[:, -1]) #Select all rows and access last column
print(number_array[:, 0:3]) #First 3 columns
print(number_array[:, 1:4]) #Skip the 1st columns
print(number_array[:, ::2]) #First 3 columns
print(number_array[:, 1::2]) #First 3 columns
print(number_array[:, ::-1]) #Reverse the columns
print(number_array[:, ::-2]) #Reverse the columns
print(number_array[0:2, 0:2]) #Selecting a quadrant for the 4 X 4 Matrix, Gives First Two Columns of First two rows.
print(number_array[0:2, 2:]) #Selecting a quadrant for the 4 X 4 Matrix
print(number_array[2:, 0:2]) #Selecting a quadrant for the 4 X 4 Matrix
print(number_array[2:, 2:]) #Selecting a quadrant for the 4 X 4 Matrix

1
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]
[ 4  8 12 16]
[ 4  8 12 16]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[ 9 10]
 [13 14]]
[[11 12]
 [15 16]]


# Arithmetic & Vectorization

## Scalar Arithmatic
Single Value Maths
Scalar - Linear Algebra Term

In [18]:
m_array = np.array([1, 2, 3])
print(m_array + 1)
print(m_array - 2)
print(m_array * 3)
print(m_array / 4)
print(m_array ** 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


## Vector Arithmatic
Vector is another Linear Algebra Term, Vector is another Single Dimension, such as an 1D List whereas Scalar is a single term.

In [19]:
v_array = np.array([1, 2, 3])
# Square root of Array
print(np.sqrt(v_array))
n_array = np.array([1.01, 2.5, 3.99])
print(np.round(n_array))
print(np.floor(n_array))
print(np.ceil(n_array))
print(np.pi)

[1.         1.41421356 1.73205081]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793


In [20]:
# Exercise
radii = np.array([1, 2, 3])
print(np.pi * radii ** 2) # Exponentiation evaluated first. Area of Circle = pi(r)^2

[ 3.14159265 12.56637061 28.27433388]


In [21]:
# Element Wise Airithmatic
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [22]:
# Comparision Operators

scores = np.array([91, 55, 100, 73, 82, 64])

print(scores == 100) # Retuns a boolean array
print(scores >= 60) # Retuns a boolean array
print(scores > 60) # Retuns a boolean array
print(scores < 60) # Retuns a boolean array

[False False  True False False False]
[ True False  True  True  True  True]
[ True False  True  True  True  True]
[False  True False False False False]


In [23]:
scores[scores < 60] = 0
print(scores)

[ 91   0 100  73  82  64]


# Broadcasting
Broadcasting allows NumPY to perform operations on arrays with different shapes by virtually expanding dimensions so they match the larger array's shape.

Two arrays are compatible when the dimensions have the same size or one of the dimensions has a size of 1.

In [24]:
array_1 = np.array([[1, 2, 3, 4]]) #2D Array with 1 row
array_2 = np.array([[1], [2], [3], [4]]) # 2D Array with 4 rows

print(array_1.shape)
print(array_2.shape)
# Broadcasting Possible
print(array_1 * array_2) #4 X 4 Matrix #Broading the array by virtually expanding the dimensions.

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [25]:
array_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) #2D Array with 1 row
array_2 = np.array([[1], [2], [3], [4]]) # 2D Array with 4 rows

print(array_1.shape)
print(array_2.shape)

# Rules:
# When matching dimensions they either need to be the same number or one of them has to have a value of 1.
# We read the dimensions from Right to Left
# Broadcasting not possible.
# print(array_1 * array_2) #Broading the array by virtually expanding the dimensions.

(2, 4)
(4, 1)


In [26]:
array_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]) #2D Array with 1 row
array_2 = np.array([[1], [2], [3], [4]]) # 2D Array with 4 rows

print(array_1.shape)
print(array_2.shape)

# Rules:
# When matching dimensions they either need to be the same number or one of them has to have a value of 1.
# We read the dimensions from Right to Left
# Broadcasting possible.
print(array_1 * array_2) #Broading the array by virtually expanding the dimensions.

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [27]:
array_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]) #2D Array with 1 row
array_2 = np.array([[1, 2], [2, 3], [3, 4], [4, 5]]) # 2D Array with 4 rows

print(array_1.shape)
print(array_2.shape)

# Rules:
# When matching dimensions they either need to be the same number or one of them has to have a value of 1.
# We read the dimensions from Right to Left
# Broadcasting not possible as no. of columns dont match but the rows still match
# print(array_1 * array_2) #Broading the array by virtually expanding the dimensions.

(4, 4)
(4, 2)


In [28]:
# Create a Multiplication Table via Broadcasting
row_array = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
column_array = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print(row_array.shape)
print(column_array.shape)

print(row_array * column_array)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


# Aggregate Functions
Aggregate Functions summarize data and typically return a single value.

In [29]:
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])
print(np.sum(array))

55


In [30]:
print(np.mean(array))

5.5


In [31]:
print(np.std(array)) # Standard Deviation

2.8722813232690143


In [32]:
print(np.var(array)) # Square of Standard Deviation, i.e., Variance

8.25


In [33]:
print(np.min(array)) # Standard Deviation

1


In [34]:
print(np.max(array)) # Standard Deviation

10


In [35]:
print(np.argmin(array)) # Index of Smallest Value

0


In [36]:
print(np.argmax(array)) # Index of Greatest Value

9


In [37]:
print(np.sum(array, axis = 0)) # Appying func to sum all columns
print(np.sum(array, axis = 1)) # Appying func to sum the rows

[ 7  9 11 13 15]
[15 40]


# Filtering
It refers to the process of selecting elements from an array that matches a given condition.

Filtering out elements that don't match a condition

In [40]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18] # Boolean Indexing
adults = ages[(ages >= 18) & (ages < 65)]
adults1 = ages[(ages < 18) | (ages >= 65)]
seniors = ages[ages >= 65]
evens = ages[ages % 2 == 0]
odds = ages[ages % 2 != 0]
print(ages)
print(teenagers)
print(adults)
print(adults1)
print(seniors)
print(evens)
print(odds)

[[21 17 19 20 16 30 18 65]
 [39 22 15 99 18 19 20 21]]
[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]


In [ ]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])
adults2 = np.where(ages >= 18, ages, 0) # 0 is fill value
# adults2 = np.where(ages >= 18, ages, np.nan)
# adults2 = np.where(ages >= 18, ages, -1)
print(adults2) # USe where clause only when you have to preseve the original shape as it slower than filtering

# Random Numbers

In [46]:
rng = np.random.default_rng() # Random Number Generator
print(rng.integers(low = 1, high = 7)) # High is exclusive
print(rng.integers(1, 101, size = 3)) # Stored in 1D Array
print(rng.integers(1, 101, size = (3, 2))) # Random numbers stored in 2D array

2
[89 15 66]
[[78 60]
 [14 48]
 [ 1 49]]


In [48]:
rng = np.random.default_rng(seed = 1) # Random Number Generator
print(rng.integers(low = 1, high = 7)) # High is exclusive
print(rng.integers(1, 101, size = 3)) # Stored in 1D Array
print(rng.integers(1, 101, size = (3, 2))) # Random numbers stored in 2D array

3
[52 76 96]
[[ 4 15]
 [83 95]
 [25 32]]


In [50]:
print(np.random.uniform()) #Uniform Distribution
print(np.random.uniform(low = -1, high = 1, size = 3)) #1D Array
print(np.random.uniform(low = -1, high = 1, size = (3, 2))) #1D Array

0.6719719343416797
[-0.18991414  0.44662267 -0.50581086]


In [ ]:
np.random.seed(seed = 1)
print(np.random.uniform(low = -1, high = 1, size = (3, 2))) #1D Array

In [ ]:
rng = np.random.default_rng()
array = np.array([1, 2, 3, 4, 5])
print(array)
rng.shuffle(array)
print(array)

In [ ]:
rng = np.random.default_rng()
fruits = np.array(["Apple", "Orange", "Bananna", "Coconut", "Pineapple"])
fruit = rng.choice(fruits)
fruits = rng.choice(fruits, size = 3)
fruits = rng.choice(fruits, size = (3, 3))
print(fruit)